version: '3'
services:
  dsl:
    build: .
    environment:
      CASC_JENKINS_CONFIG: /gitrepo/configuration-as-file
      GITHUB_PASS: $GITHUB_PASS
      GLOBAL_LIBRARIES_REPOSITORY: /gitrepo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/gitrepo
    command:
      - -f
      - /gitrepo/Jenkinsfiles/dsl/Jenkinsfile
  simple:
    build: .
    environment:
      CASC_JENKINS_CONFIG: /gitrepo/configuration-as-file
      GITHUB_PASS: $GITHUB_PASS
      GLOBAL_LIBRARIES_REPOSITORY: /gitrepo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/gitrepo
    command:
      - -f
      - /gitrepo/Jenkinsfiles/simple/Jenkinsfile