@Library('utils@master') _

mypipeline {
  operations = [
    format: [
      script: 'echo "format things"'
    ],
    build: [
      script: 'echo "build things"',
      image: 'busybox:latest'
    ]
  ]
}
